services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka-tdg
    hostname: kafka-tdg
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      # Broker
      KAFKA_BROKER_ID: "1"

      # ZooKeeper
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      # Listeners
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"

      # Topic / ISR
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_MIN_INSYNC_REPLICAS: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"

      # Topic policy
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

    restart: unless-stopped
